### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by paul-huszak**

### CODE REVIEW

**Comment by paul-huszak** [comment]
Sorry for the late PR.

**Comment by fjlopez** [comment]
`count` should be used in the URL of L65 to give a limit to the number of responses. 
 
https://github.com/paul-huszak/lab5-soa/blob/eb91dcba06a3fa0d410c524beeceef014cd90293/src/main/kotlin/soa/camel/Application.kt#L51-L65

**Comment by paul-huszak** [comment]
Fixed the bug. Added "count" into L62.

**Comment by fjlopez** [comment]
Merged!

**Pull request merged**
