### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ibon2**

### CODE REVIEW

**Comment by Ibon2** [comment]
He eliminado el anterior pull request sin querer

**Comment by fjlopez** [comment]
Fix incorrect code:
```kotlin
            .toD("twitter-search:\${header.keywords}\${body}")
```

**Comment by fjlopez** [comment]
`count` header should be used in the twitter URL.

**Comment by Ibon2** [comment]
Corrected now

**Comment by fjlopez** [comment]
Merged!

**Pull request merged**
