### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by SergioGCH**

### CODE REVIEW

**Comment by fjlopez** [comment]
Your code does not compile:
```
 val q = exchange.getIn().getHeader("keywords")?.toString()
 val command = q.replace("max:", "?count=")
```

`q` is of type `String?` (i.e. `String` or `null`).  Only safe (?.) or non-null asserted (!!.) calls are allowed on `String?`.

Please, fix this bug ASAP.

**Comment by fjlopez** [comment]
Just update the bug, and warn me here.

**Comment by SergioGCH** [comment]
Bug is already fixed.

**Comment by fjlopez** [comment]
Fixed! **PR accepted**

**Pull request merged**
