### PR TITLE
Finished pr5

### PR DESCRIPTION
**Pull request by 798523**

### CODE REVIEW

**Comment by fjlopez** [comment]
Code is incomplete. Fix this:

```kotlin
            .toD("twitter-search:\${header.keywords}") // ?count=\${header.counts}
```

**Comment by fjlopez** [comment]
Code continue to be incomplete. `counts` header should be used in the URL.

**Comment by fjlopez** [comment]
@798523 please review this issue.

**Comment by 798523** [comment]
Sorry for the delay. I totally forgot it. Sorry again

**Pull request closed without merging**
