### PR TITLE
Enrique Ruiz Gift

### PR DESCRIPTION
**Pull request by TheRealFreeman**

### CODE REVIEW

**Comment by fjlopez** [comment]
The JS side is missing. As you are not using STOMP, it is quite straight:

```js
const socket = new WebSocket('ws://localhost:8080/ws'); // assuming you have your ws enpdoint there.

openConnection = false;
socket.addEventListener('open', function (event) {
    openConnection = true;
    socket.send('Hello Server!');
});

socket.addEventListener('message', function (event) {
    // event.data contains the tweets
});

// in the handler of the click to search
if (openConnection) {
    socket.send(query);
}

```

**Comment by TheRealFreeman** [comment]
I added the JS client as requested, I also want to point out I made a test with Java client to test the websocket endpoint.

**Comment by fjlopez** [comment]
Don't worry, you have the :gift: but I would like to polish the code before closing the issue. 

I was aware of your work with the tests but it is a test, not a client ;-) . Let me check today the JS code.

**Comment by TheRealFreeman** [comment]
Sure, I´ll wait.  By the way, just in case it helps, I checked and I am receiving the tweets on the client side, the problem is when rendering them out with Mustache.render.

**Comment by fjlopez** [comment]
It is a bit tricky but feasible. It requires:

- add the dependency `compile("org.apache.camel:camel-jackson:3.6.0")` (convert POJO to JSON)
- add just before the `.to("websocket://localhost:50000/twitterWS")` the following snippet:
 ```java
      .marshal().json() // twitter response to JSON object 
      .transform().simple("${body}", String.class) // JSON object to String 
 ```
- and then, in the JavaScript 
 ```js
        $("#resultsBlock").html(Mustache.render(template, JSON.parse(event.data))); // String to JSON
 ```
And works!!! Please add these changes to your code and test it. Meanwhile I will merge your PR.

**Comment by TheRealFreeman** [comment]
It works! I´ve tested it and pushed the changes to my gift branch. Thank you very much!

**Pull request merged**
