### PR TITLE
Primary goal

### PR DESCRIPTION
**Pull request by dmarcob**

### CODE REVIEW

**Comment by fjlopez** [comment]
Instead of

```kotlin
  var qFormatted = q.orEmpty().replace(" max:","?count=")
```

You should add

```kotlin
 from(DIRECT_ROUTE)
  .process { exchange ->
     // do something with the `exchange in` and update the header `keywords`.
  }
  .toD("twitter-search:\${header.keywords}")
```

**Comment by fjlopez** [comment]
Instead of

```kotlin
  var qFormatted = q.orEmpty().replace(" max:","?count=")
```

You should add

```kotlin
 from(DIRECT_ROUTE)
  .process { exchange ->
     // do something with the `exchange in` and update the header `keywords`.
  }
  .toD("twitter-search:\${header.keywords}")
```

**Comment by dmarcob** [comment]
I've updated this PR with the change requested. @fjlopez

**Comment by fjlopez** [comment]
**PR accepted**

**Pull request merged**
